language: c

dist: trusty

os:
  - linux
  # - osx

# TODO I think the only sensible way to get macOS testing to work is if
# we have a script that downloads and extracts a pre-built LLVM, since
# homebrew seems to either build from source, or somehow doesn't have
# llc available (maybe it's just not in your path though?)

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - llvm-6.0-dev
      - llvm-6.0-tools

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm@6 --with-toolchain ; fi

script:
  - ./test/run.sh
  - make unified
